version: 0.0
os: linux

# 배포 파일은 필요 없으므로 빈 리스트로 둡니다.
files:
  - source: /
    destination: /home/ec2-user/jhm-cd-test

hooks:
  BeforeInstall:
    - location: scripts/stop_old_container.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/start_new_container.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/check_health.sh
      timeout: 60
      runas: root

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 30
      runas: root
